/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/ocs/v2.php/apps/fts_sql/settings/language": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /**
         * Store the text search language every future index write will stem with
         * @description This endpoint requires admin access
         */
        readonly put: operations["settings-put-language"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/ocs/v2.php/apps/fts_sql/settings/content-bytes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /**
         * Store how many bytes of extracted text are indexed per document
         * @description This endpoint requires admin access
         */
        readonly put: operations["settings-put-content-bytes"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly OCSMeta: {
            readonly status: string;
            readonly statuscode: number;
            readonly message?: string;
            readonly totalitems?: string;
            readonly itemsperpage?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly "settings-put-language": {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required to be true for the API request to pass */
                readonly "OCS-APIRequest": boolean;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    /** @description a text search configuration name, one of those the running engine itself reports */
                    readonly language: string;
                };
            };
        };
        readonly responses: {
            /** @description Language stored */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly ocs: {
                            readonly meta: components["schemas"]["OCSMeta"];
                            readonly data: {
                                readonly language: string;
                            };
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly ocs: {
                            readonly meta: components["schemas"]["OCSMeta"];
                            readonly data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly ocs: {
                            readonly meta: components["schemas"]["OCSMeta"];
                            readonly data: unknown;
                        };
                    };
                };
            };
            /** @description The running engine does not report this language */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly ocs: {
                            readonly meta: components["schemas"]["OCSMeta"];
                            readonly data: {
                                readonly message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    readonly "settings-put-content-bytes": {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required to be true for the API request to pass */
                readonly "OCS-APIRequest": boolean;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    /**
                     * Format: int64
                     * @description the per-document content budget, in bytes
                     */
                    readonly contentBytes: number;
                };
            };
        };
        readonly responses: {
            /** @description Budget stored */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly ocs: {
                            readonly meta: components["schemas"]["OCSMeta"];
                            readonly data: {
                                /** Format: int64 */
                                readonly contentBytes: number;
                            };
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly ocs: {
                            readonly meta: components["schemas"]["OCSMeta"];
                            readonly data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly ocs: {
                            readonly meta: components["schemas"]["OCSMeta"];
                            readonly data: unknown;
                        };
                    };
                };
            };
            /** @description The budget is not a positive number of bytes */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly ocs: {
                            readonly meta: components["schemas"]["OCSMeta"];
                            readonly data: {
                                readonly message: string;
                            };
                        };
                    };
                };
            };
        };
    };
}
